
name: Kernel Build CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: panchajanya1999/archlinux:latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup env
        run: pacman -Syu --needed --noconfirm wget base-devel xmlto inetutils bc cpio python-sphinx python-sphinx_rtd_theme graphviz imagemagick git python2 python zip 
      - name: Build Kernel
        run: |
          export token=${TELEGRAM_BOT_TOKEN}
          bash build.sh
        env:
          TOKEN: ${{ secrets.TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          KERNEL_SOURCE: ${{ secrets.KERNEL_SOURCE }}
          KERNEL_NAME: ${{ secrets.KERNEL_NAME }}
          KERNEL_DEFCONFIG: ${{ secrets.KERNEL_DEFCONFIG }}
          DEVICE_CODENAME: ${{ secrets.DEVICE_CODENAME }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          ANYKERNEL: ${{ secrets.ANYKERNEL }}
